language: generic
sudo: required
services:
 - docker

before-install:
 - docker build -t dardodel/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true dardodel/docker-react npm run test
